# Docker compose version used
version: '3.8'
# Services or containers to be used
services:
  db-mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'polls'
    volumes:
      - ~/polls/data:/var/lib/mysql
    networks:
      - polls-network

  polls-dc:       # name of the service/container
    image: rafaelrfq/polls-sl
    ports:
      - 80:8080
    environment:    # environment variables
      - spring.datasource.url=jdbc:mysql://db-mysql:3306/polls
      - spring.datasource.username=root
      - spring.datasource.password=password
      - MYSQL_HOST=db-mysql
    networks:    # network to connect containers
      - polls-network
    volumes:
      - polls-volume:/tmp/
    depends_on:   # indicates what to load first
      - db-mysql

networks:
  polls-network:

volumes:
  polls-volume: