# Docker compose version used
version: '3.8'
# Services or containers to be used
services:
  polls-dc:       # name of the service/container
    image: rafaelrfq/polls-dc
    ports:
      - 80:8080
    environment:    # environment variables
      - spring.datasource.url=jdbc:mysql://db-mysql:3306/polls
    networks:    # network to connect containers
      - polls-network
    volumes:
      - polls-volume:/tmp/
    depends_on:   # indicates what to load first
      - db-mysql

  db-mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=polls
    volumes:
      - ~/polls/data:/var/lib/mysql
    networks:
      - polls-network

networks:
  polls-network:

volumes:
  polls-volume: