# Docker compose version used
version: '3.8'
# Services or containers to be used
services:
  polls-dc:       # name of the service/container
    build: .
    ports:
      - 80:8080
    environment:    # environment variables
      - spring.datasource.url=jdbc:mysql://db-mysql:3306/polls
    networks:    # network to connect containers
      - polls-network
    volumes:
      - polls-volume:/tmp/
    depends_on:   # indicates what to load first
      - db-mysql

  db-mysql:
    image: mysql:5.7.26
    ports:
      - 33006:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=root
      - MYSQL_DATABASE=polls
    volumes:
      - ~/polls/data:/var/lib/mysql
    networks:
      - polls-network

networks:
  polls-network:

volumes:
  polls-volume: